# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import object_tracking_pb2 as grpc__test_dot_object__tracking__pb2


class ObjectTrackingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Track = channel.unary_stream(
                '/objecttracking.ObjectTracking/Track',
                request_serializer=grpc__test_dot_object__tracking__pb2.EmptyMsg.SerializeToString,
                response_deserializer=grpc__test_dot_object__tracking__pb2.Object.FromString,
                )


class ObjectTrackingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Track(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectTrackingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Track': grpc.unary_stream_rpc_method_handler(
                    servicer.Track,
                    request_deserializer=grpc__test_dot_object__tracking__pb2.EmptyMsg.FromString,
                    response_serializer=grpc__test_dot_object__tracking__pb2.Object.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'objecttracking.ObjectTracking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ObjectTracking(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Track(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/objecttracking.ObjectTracking/Track',
            grpc__test_dot_object__tracking__pb2.EmptyMsg.SerializeToString,
            grpc__test_dot_object__tracking__pb2.Object.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
